/* Builds puzzles.js from the fact-checked content in data/verified.json.
   - applies verifier verdicts (fix / drop)
   - validates every question (bounds, margins, units, dedup)
   - composes daily sets of 5 with category diversity, deterministically shuffled
   Run: node tools/assemble.js */
"use strict";
const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.join(__dirname, "..");
const EPOCH = "2026-07-27";
const MIN_MARGIN = 0.08; // answer must sit ≥8% of track span from each edge

const batches = JSON.parse(fs.readFileSync(path.join(ROOT, "data", "verified.json"), "utf8"));

function valToPos(q, v) {
  return q.scale === "log" ? Math.log(v / q.lo) / Math.log(q.hi / q.lo) : (v - q.lo) / (q.hi - q.lo);
}

// deterministic PRNG so every rebuild yields the same schedule
function mulberry32(seed) {
  return function () {
    seed |= 0; seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const questions = {};
const byCat = {};
const seenPrompts = new Set();
const report = { kept: 0, fixed: 0, dropped: 0, rejected: [] };

for (const batch of batches) {
  const verdictByIndex = {};
  for (const v of batch.verdicts || []) verdictByIndex[v.index] = v;
  byCat[batch.category] = byCat[batch.category] || [];

  batch.questions.forEach((q, i) => {
    const v = verdictByIndex[i];
    if (v && v.verdict === "drop") { report.dropped++; report.rejected.push([q.prompt, "verifier: " + v.note]); return; }
    if (v && v.verdict === "fix") {
      if (v.correctedAnswer !== undefined) q.answer = v.correctedAnswer;
      if (v.correctedLo !== undefined) q.lo = v.correctedLo;
      if (v.correctedHi !== undefined) q.hi = v.correctedHi;
      if (v.correctedPrompt) q.prompt = v.correctedPrompt;
      report.fixed++;
    }

    // hard validation — anything failing is rejected, not repaired silently
    const problems = [];
    if (!(q.lo < q.hi)) problems.push("lo >= hi");
    if (q.scale === "log" && q.lo <= 0) problems.push("log scale with lo <= 0");
    if (typeof q.answer !== "number" || !isFinite(q.answer)) problems.push("bad answer");
    if (!problems.length) {
      const p = valToPos(q, q.answer);
      if (!(p >= MIN_MARGIN && p <= 1 - MIN_MARGIN)) problems.push(`answer at ${(p * 100).toFixed(0)}% of track (needs ${MIN_MARGIN * 100}% margin)`);
    }
    if (!q.prompt || q.prompt.length > 140) problems.push("prompt missing/too long");
    if (!q.unit) problems.push("no unit");
    const key = q.prompt.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
    if (seenPrompts.has(key)) problems.push("duplicate prompt");

    if (problems.length) { report.dropped++; report.rejected.push([q.prompt, problems.join("; ")]); return; }
    seenPrompts.add(key);

    const id = batch.category + (byCat[batch.category].length + 1);
    questions[id] = {
      prompt: q.prompt, answer: q.answer, unit: q.unit, scale: q.scale,
      lo: q.lo, hi: q.hi, asOf: q.asOf || null,
      source: q.source, reveal: q.reveal, categoryName: batch.categoryName,
    };
    byCat[batch.category].push(id);
    report.kept++;
  });
}

// answer-position spread check: the midpoint must not be a tell
const positions = Object.values(questions).map((q) => valToPos(q, q.answer));
const thirds = [0, 0, 0];
positions.forEach((p) => thirds[Math.min(2, Math.floor(p * 3))]++);
console.log(`answer position spread: low ${thirds[0]} / mid ${thirds[1]} / high ${thirds[2]}`);

// compose days: shuffle within category, deal one per category per day round-robin
const rng = mulberry32(20260727);
const decks = Object.entries(byCat)
  .filter(([, ids]) => ids.length > 0)
  .map(([cat, ids]) => {
    const d = ids.slice();
    for (let i = d.length - 1; i > 0; i--) {
      const j = Math.floor(rng() * (i + 1));
      [d[i], d[j]] = [d[j], d[i]];
    }
    return { cat, ids: d, cursor: 0 };
  });

const days = [];
while (true) {
  // pick the 5 categories with the most remaining questions (keeps sets diverse to the end)
  const avail = decks.filter((d) => d.cursor < d.ids.length).sort((a, b) => (b.ids.length - b.cursor) - (a.ids.length - a.cursor));
  if (avail.length < 5) break;
  const day = avail.slice(0, 5).map((d) => d.ids[d.cursor++]);
  // shuffle question order within the day
  for (let i = day.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [day[i], day[j]] = [day[j], day[i]];
  }
  days.push(day);
}

const out =
  `/* Ballpark content pack — generated by tools/assemble.js. Do not hand-edit.\n` +
  `   ${report.kept} verified questions · ${days.length} days of puzzles. */\n` +
  `window.BALLPARK_DATA = ${JSON.stringify({ epoch: EPOCH, questions, days }, null, 1)};\n`;
fs.writeFileSync(path.join(ROOT, "puzzles.js"), out);

console.log(`kept ${report.kept} (${report.fixed} fixed), dropped ${report.dropped}, days ${days.length}`);
if (report.rejected.length) {
  console.log("\nrejected:");
  for (const [p, why] of report.rejected) console.log(`  - ${p}\n      ${why}`);
}
