/* Re-deals the daily schedule using estimability tags (data/tags.json).
   - Days already served (0..FREEZE-1) are preserved byte-for-byte.
   - Future days: 5 distinct categories, at most MAX_LOOKUP "lookup" questions,
     deterministic shuffle so reruns are stable.
   - Tags are embedded on each question for future tooling.
   Run: node tools/rebalance.js */
"use strict";
const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.join(__dirname, "..");
/* A day is frozen the moment it ships: players have answers saved against its
   index, the archive replays it, and ?d=&s= challenge links point into it.
   Re-dealing one rewrites history. This tool now only balances days appended
   after the published pack, so it must be told where the new tail starts:
     node tools/rebalance.js --from=65
   --from must be >= the number of days already published and deployed. */
const fromArg = (process.argv.find(function (a) { return a.indexOf("--from=") === 0; }) || "").split("=")[1];
if (fromArg === undefined) {
  console.error("refusing to run: pass --from=N (first day index that has NOT been published).");
  console.error("re-dealing a published day would change questions people already answered.");
  process.exit(1);
}
const FREEZE = parseInt(fromArg, 10);
const MAX_LOOKUP = 1;  // per-day budget of know-it-or-don't questions

global.window = {};
require(path.join(ROOT, "puzzles.js"));
const DATA = global.window.BALLPARK_DATA;

const tagBatches = JSON.parse(fs.readFileSync(path.join(ROOT, "data", "tags.json"), "utf8"));
const tagById = {};
for (const b of tagBatches) for (const t of b.tags) tagById[t.id] = t.tag;

let untagged = 0;
for (const id of Object.keys(DATA.questions)) {
  if (!tagById[id]) { tagById[id] = "anchor"; untagged++; }
  DATA.questions[id].tag = tagById[id];
}
if (untagged) console.log(`warning: ${untagged} untagged questions defaulted to "anchor"`);

function mulberry32(seed) {
  return function () {
    seed |= 0; seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const rng = mulberry32(20260730);
const shuffle = (a) => {
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
};

const frozen = DATA.days.slice(0, FREEZE);
const used = new Set(frozen.flat());

const catOf = (id) => id.replace(/\d+$/, "");
const decks = {};
for (const id of Object.keys(DATA.questions)) {
  if (used.has(id)) continue;
  (decks[catOf(id)] = decks[catOf(id)] || []).push(id);
}
// weave each deck's lookups evenly among its estimable questions — clustering
// them at the tail would make the last scheduled week all-trivia
for (const cat of Object.keys(decks)) {
  const d = shuffle(decks[cat]);
  const est = d.filter((id) => tagById[id] !== "lookup");
  const lk = d.filter((id) => tagById[id] === "lookup");
  const woven = est.slice();
  lk.forEach((id, k) => {
    const pos = Math.min(woven.length, Math.round(((k + 1) * (est.length + lk.length)) / (lk.length + 1)));
    woven.splice(pos, 0, id);
  });
  decks[cat] = woven;
}

const future = [];
for (;;) {
  const avail = Object.entries(decks)
    .filter(([, ids]) => ids.length > 0)
    .sort((a, b) => b[1].length - a[1].length);
  if (avail.length < 5) break;
  const day = [];
  let lookups = 0;
  for (const [cat, ids] of avail.slice(0, 5)) {
    // take the first question that respects the day's lookup budget
    let pick = ids.findIndex((id) => tagById[id] !== "lookup" || lookups < MAX_LOOKUP);
    if (pick === -1) pick = 0;
    const id = ids.splice(pick, 1)[0];
    if (tagById[id] === "lookup") lookups++;
    day.push(id);
  }
  future.push(shuffle(day));
}

DATA.days = frozen.concat(future);

// sanity: frozen prefix intact, day shape valid, lookup budget respected
const counts = { gut: 0, anchor: 0, lookup: 0 };
Object.keys(DATA.questions).forEach((id) => counts[tagById[id]]++);
const overBudget = future.filter((d) => d.filter((id) => tagById[id] === "lookup").length > MAX_LOOKUP);
console.log(`tags: gut ${counts.gut} / anchor ${counts.anchor} / lookup ${counts.lookup}`);
console.log(`days: ${FREEZE} frozen + ${future.length} re-dealt = ${DATA.days.length}`);
console.log(`days exceeding lookup budget: ${overBudget.length}`);

const out =
  `/* Ballpark content pack — generated by tools/assemble.js + tools/rebalance.js. Do not hand-edit.\n` +
  `   ${Object.keys(DATA.questions).length} verified questions · ${DATA.days.length} days · estimability-balanced. */\n` +
  `window.BALLPARK_DATA = ${JSON.stringify({ epoch: DATA.epoch, questions: DATA.questions, days: DATA.days }, null, 1)};\n`;
fs.writeFileSync(path.join(ROOT, "puzzles.js"), out);
console.log("wrote puzzles.js");
